### ISSUE TITLE
Domain Connect DynDns unsupported

### ISSUE THREAD

**Issue by stefanjb-it** [Domain-Connect/DomainConnectDDNS-Python#55]
Since the move of my domain-connect-service instance from one VM to another VM, the synchronization is not working anymore. On the old host version, 0.4.x was installed and on the version 0.9.0 is installed. Since then every time I want to set up a domain (that was used on the old host) I get the following error:

```
*** domain-connect-dyndns 0.0.9 ***

Domain doesn't support Domain Connect.
```

But resetting the domain also doesn't solve the problem.
**My DNS provider is 1&1(IONOS).**

**Comment by pawel-kow** [comment]
@stefanjb-it my suspect would be that the domain does not have `_domainconnect` DNS record any longer.
One way is to restore it (in IONOS reset domain usage function).
The other way is to copy setting.txt file from the old VM to the new one (however in this case the old VM needs to stop calling DynDNS service, otherwise on the token rollover one of them will cease to work).

**Comment by stefanjb-it** [comment]
Thx for the quick answer.
I have reset every domain and added the `_domainconnect` DNS entry and now it is working.
