### ISSUE TITLE
Domain-Update broken

### ISSUE THREAD

**Issue by Samurai1201** [Domain-Connect/DomainConnectDDNS-Python#58]
After some time of everything being fine, this error popped up:

```
Read xxx.xxxxxx.org config.
  IP xxx.xxx.xxx.xxx found in A record
  Public IPv4 address: xxx.xxx.xxx.xxx
No nameservers avalaible for "xxxxxxx.org"
Could not update DNS records.
```

I cant seem to find any reason/nor understand why this randomly occured

Does anybody know what to do?

**Comment by pawel-kow** [comment]
Looking at [the source code](https://github.com/search?q=org%3ADomain-Connect+No+nameservers+avalaible+for&type=code) it seems like resolution of the TXT record _domainconnnect.xxxxxxx.org is not working fine and an error seems to be due to Nameserver configuration.

You may use tools like https://www.zonemaster.net/ to check your domain configuration or https://mxtoolbox.com/ to see if the TXT record resolves OK from the outside.

**Comment by Samurai1201** [comment]
Ive tried both tools, but both dont seem to even find a record published for this domain

**Comment by pawel-kow** [comment]
So I think you need to figure out your domain configuration. The tool won't work if the DNS is not configured properly.
